---
init_cmd: 
  source $HOME/spqrel/spqrel_launch/worktree/spqrel_tools/setup.bash;
windows:
- name: init
  panes:
  - cd $SPQREL_HOME/scripts; python postureinit.py
- name: config
  panes:
  - $SPQREL_TOOLS/scripts/config_manager.py
- name: navigation
  panes:
  - cd $SPQREL_HOME/bin; ./pepper_head_control --head_pitch 0.2
  - cd $SPQREL_HOME/bin; ./depth2laser_naoqi --angle_min -0.6 --angle_max 0.6 --range_max 8 --num_ranges 1000 --laser_z 0.6
  - cd $SPQREL_HOME/bin; ./pepper_localizer --map $MAP --initial_pose_x 0 --initial_pose_y
    0 --initial_pose_theta 0 --use_d2l 1
  - sleep 5; cd $SPQREL_HOME/bin; ./pepper_planner --map $MAP --use_d2l 1
  - sleep 5; cd $SPQREL_HOME/worktree/spqrel_navigation/src/topological_navigation/scripts/;
    ./topological_navigation.py --tmap $TMAP
- name: speech
  panes:
  - cd $SPQREL_HOME/slu4p; python speech_to_text/asr.py --vocab resources/nuance_dictionary.txt
  - cd $SPQREL_HOME/slu4p; python speech_to_text/google_client.py
  - sleep 6; cd $SPQREL_HOME/slu4p; python dialogue_management/dialogue_manager.py
    -a resources/aiml_kbs/spqrel
  - sleep 9; cd $SPQREL_HOME/slu4p; python text_to_speech/text_to_speech.py
- name: lu4r
  panes:
  - cd $SPQREL_HOME/slu4p; python language_understanding/language_understanding.py
  - sleep 3; cd $SPQREL_HOME/slu4p; python speech_reranking/reranker.py --noun-dictionary
    resources/noun_dictionary.txt --verb-dictionary resources/verb_dictionary.txt
    --nuance-grammar resources/nuance_grammar.txt
- name: pnp
  panes:
  - cd $SPQREL_HOME; bin/pnp_naoqi
  - cd $SPQREL_HOME/actions; python init_actions.py
- name: ui
  panes:
  - cd $SPQREL_HOME/worktree/spqrel_tools/ui; python ./spqrel_ui.py
  - cd $SPQREL_HOME/worktree/spqrel_tools/modim_actions/cocktail_party; python -m SimpleHTTPServer 8000
  - cd $SPQREL_HOME/worktree/modim/src/GUI; python ws_server.py -robot pepper 
  - sleep 5; cd $SPQREL_HOME/worktree/pepper_tools/tablet/; python show_web.py --url http://198.18.0.1:8127/
  #- cd $SPQREL_HOME/worktree/robot_blockly; python scripts/pywebserver.py
  #- cd $SPQREL_HOME/worktree/robot_blockly; python scripts/robot_blockly_backend.py
- name: dataset
  panes:
  - cd $SPQREL_HOME/worktree/spqrel_tools/naoqibag; python ./naoqibag.py --pause True
    --rate 5 --keys all.key --path $SPQREL_HOME/ --o keys.log
- name: task_start
  panes:
  - "#cd $SPQREL_HOME/actions; ./action_cmd.py -a   -p   -c start"
  - "#cd $SPQREL_HOME/plans; ./run_plan.py"
