
_config_example:
  general: "everything is encoded as dictionaries, every key is translated into an URI like path, e.g. this text is stored in memory under /_config_example/general"
  sub_feature: 
    - "lists are natively supported, so" 
    - "this list will all be stored under /_config_example/sub_feature"
    - 
      k1: "it is not recommended to do, e.g. a list of dicts, as Qi doesn't handle this well (translates the dict into a list of pairs). Avoid! Better use a JSON string in this case"
  "$json:foo": 
    - "in fact, the magic prefix key '$json' will store everything under this key directly as a JSON string, here, this will all end up in /_config_example/foo"
    - "more text"
    - 
      complicated: true
      another_level:
        super: "yeah"


location_mapping:
  desk: sofafront
  left+rack: backdoorin
  kitchen: kitchendoor
  drinks: fridge
SPR:
  orientation: 135
  place: sofafront

# navigateto_^SPR/place
# turn_^SPR/orientation

